name: Flutter

on:
  push:
    branches: [ "main", "Development" ]
    paths:
      - 'flutter/**'
      - '.github/workflows/flutter.yml'

  pull_request:
    branches: [ "main", "Development" ]
    paths:
      - 'flutter/**'
      - '.github/workflows/flutter.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    defaults:
      run:
        working-directory: flutter/scanner_cooker

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build appbundle
